---
  name: Semantic Release CI
  
  on:
    push:
      branches:
        - main
        - '[0-9]+.[0-9]+.x'
    workflow_dispatch:
  defaults:
    run:
      shell: bash
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  jobs:
    release-please:
      permissions:
        contents: write
        pull-requests: write
      runs-on: ubuntu-latest
      outputs:
        releases_created: ${{ steps.release.outputs.releases_created }}
        tag_name: ${{ steps.release.outputs.tag_name }}
  
      steps:
        - name: Checkout the code
          uses: actions/checkout@v3
  
        - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
          id: release
          with:
            command: manifest
            token: ${{secrets.GITHUB_TOKEN}}
            default-branch: main
            release-type: simple
